const google_regions = {
    "asia-east1": "Changhua County, Taiwan, APAC",
    "asia-east2": "Hong Kong, APAC",
    "asia-northeast1": "Tokyo, Japan, APAC",
    "asia-northeast2": "Osaka, Japan, APAC",
    "asia-northeast3": "Seoul, South Korea, APAC",
    "asia-south1": "Mumbai, India APAC",
    "asia-south2": "Delhi, India APAC",
    "asia-southeast1": "Jurong West, Singapore, APAC",
    "asia-southeast2": "Jakarta, Indonesia, APAC",
    "australia-southeast1": "Sydney, Australia, APAC",
    "australia-southeast2": "Melbourne, Australia, APAC",
    "europe-central2": "Warsaw, Poland, Europe",
    "europe-north1": "Hamina, Finland, Europe",
    "europe-southwest1": "Madrid, Spain, Europe",
    "europe-west1": "St. Ghislain, Belgium, Europe",
    "europe-west2": "London, England, Europe",
    "europe-west3": "Frankfurt, Germany Europe",
    "europe-west4": "Eemshaven, Netherlands, Europe",
    "europe-west6": "Zurich, Switzerland, Europe",
    "europe-west8": "Milan, Italy, Europe",
    "europe-west9": "Paris, France, Europe",
    "northamerica-northeast1": "Montr\u00e9al, Qu\u00e9bec, North America",
    "northamerica-northeast2": "Toronto, Ontario, North America",
    "southamerica-east1": "Osasco, S\u00e3o Paulo, Brazil, South America",
    "southamerica-west1": "Santiago, Chile, South America",
    "us-central1": "Council Bluffs, Iowa, North America",
    "us-east1": "Moncks Corner, South Carolina, North America",
    "us-east4": "Ashburn, Virginia, North America",
    "us-east5": "Columbus, Ohio, North America",
    "us-south1": "Dallas, Texas, North America",
    "us-west1": "The Dalles, Oregon, North America",
    "us-west2": "Los Angeles, California, North America",
    "us-west3": "Salt Lake City, Utah, North America",
    "us-west4": "Las Vegas, Nevada, North America"
};

const azure_regions = {
    "asiapacificeast": "Hong Kong",
    "asiapacificsoutheast": "Singapore",
    "australiacentral": "Canberra",
    "australiaeast": "New South Wales",
    "australiasoutheast": "Victoria",
    "brazilsouth": "S\u00e3o Paulo State",
    "canadacentral": "Toronto",
    "canadaeast": "Quebec City",
    "centralindia": "Pune",
    "chinaeast": "Shanghai",
    "chinaeast2": "Shanghai",
    "chinanorth": "Beijing",
    "chinanorth2": "Beijing",
    "chinanorth3": "Hebei",
    "europenorth": "Ireland",
    "europewest": "Netherlands",
    "francecentral": "Paris",
    "germanywestcentral": "Frankfurt",
    "japaneast": "Tokyo, Saitama",
    "japanwest": "Osaka",
    "koreacentral": "Seoul",
    "norwayeast": "Oslo",
    "qatarcentral": "Doha",
    "southafricanorth": "Johannesburg",
    "southcentralindia": "Hyderabad",
    "southindia": "Chennai",
    "swedencentral": "G\u00e4vle",
    "switzerlandnorth": "Z\u00fcrich",
    "uaenorth": "Dubai",
    "unitedkingdomsouth": "London",
    "unitedkingdomwest": "Cardiff",
    "uscentral": "Iowa",
    "usdodcentral": "Iowa",
    "usdodeast": "Virginia",
    "useast": "Virginia",
    "useast2": "Virginia",
    "usgovarizona": "Arizona",
    "usgovtexas": "Texas",
    "usgovvirginia": "Virginia",
    "usnorthcentral": "Illinois",
    "ussouthcentral": "Texas",
    "uswest": "California",
    "uswest2": "Washington",
    "uswest3": "Arizona",
    "uswestcentral": "Wyoming"
};

const aws_regions = {
    "af-south-1": "Africa (Cape Town)",
    "ap-east-1": "Asia Pacific (Hong Kong)",
    "ap-northeast-1": "Asia Pacific (Tokyo)",
    "ap-northeast-2": "Asia Pacific (Seoul)",
    "ap-northeast-3": "Asia Pacific (Osaka)",
    "ap-south-1": "Asia Pacific (Mumbai)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
    "ap-southeast-2": "Asia Pacific (Sydney)",
    "ap-southeast-3": "Asia Pacific (Jakarta)",
    "ca-central-1": "Canada (Central)",
    "eu-central-1": "Europe (Frankfurt)",
    "eu-north-1": "Europe (Stockholm)",
    "eu-south-1": "Europe (Milan)",
    "eu-west-1": "Europe (Ireland)",
    "eu-west-2": "Europe (London)",
    "eu-west-3": "Europe (Paris)",
    "me-central-1": "Middle East (UAE)",
    "me-south-1": "Middle East (Bahrain)",
    "sa-east-1": "South America (S\u00e3o Paulo)",
    "us-east-1": "US East (N. Virginia)",
    "us-east-2": "US East (Ohio)",
    "us-west-1": "US West (N. California)",
    "us-west-2": "US West (Oregon)"
};

